language: go

go:
  - 1.6
  - tip

before_install:
  - go get golang.org/x/tools/cmd/vet
  - go get github.com/golang/lint/golint
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

script: 
  - golint ./...
  - go vet ./...
  - go test -v ./... -parallel 10 -covermode=count -coverprofile=coverage.out

after_success:
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken pPb4iPuq9LJh2anNKGwVJbhZqi2w5XJbs
